### ISSUE TITLE
Make release?

### ISSUE THREAD

**Issue by jbohren** [osrf/osrf_pycommon#9]
A major PR in `catkin_tools` (https://github.com/catkin/catkin_tools/pull/196) relies on this package, but it has yet to be released into pypi. Is that something that can happen in the near future?

**Comment by davetcoleman** [comment]
+1 to releasing into pypi

**Comment by wjwwood** [comment]
I'll release this before we merge that pr, but I think there will potentially be more changes here before that happens. That's why I've put off releasing this. Nothing that uses this is released at the moment.

**Comment by mikepurvis** [comment]
The last change here was 3+ months ago. Is there something particular which gates a 0.1 release of this?

**Comment by wjwwood** [comment]
Because nothing that uses it has been released yet. I'd rather wait until we're ready to release the next version of `catkin_tools` before doing so.

**Comment by wjwwood** [comment]
Also, because I need to fix up the documentation before releasing. Some of the examples (especially as they relate to `asyncio`) are in need of attention. But it shouldn't be too much longer since we're closing in on a next release of `catkin_tools` and I have more time to spend on this since we just finished a ROS 2 release.

**Comment by mikepurvis** [comment]
We're using catkin_tools 0.4.0 from source, and it's a pain to have to separately also install this package from source.

I also have a side project I'd like to use it for, but I think I will avoid for now, and maybe port later when there's a release.

**Comment by davetcoleman** [comment]
I agree with mikepurvis - I wanted to help test the latest development of catkin_tools but this dependency, and related complications, thwarted me

**Comment by wjwwood** [comment]
I'm really trying to understand, but it's hard for me to reconcile the sentiments "I install catkin_tools from source (and will continue to do so)" and "it's a burden to install this from source, even once". I consider it to be a bit of an exaggeration.

I take the point and I will release this as soon as can, but badgering me about it just takes away from the time I have to actually work on this.

**Comment by wjwwood** [comment]
Oh, actually now I remember a technical reason why I never released this. `trollius`, which is required for Python 2.x support, does not have a Ubuntu package. I'll have to figure out what to do there... It might be some time before I find a solution to that.

**Comment by mikepurvis** [comment]
@davetcoleman If you want to try out the new catkin_tools, I believe the lowest friction method is:

```
pip install git+git://github.com/osrf/osrf_pycommon.git
pip install git+git://github.com/catkin/catkin_tools
```

Apply sudo if not in a virtualenv. Ignore scary warnings about trollius being deprecated.

**Comment by jbohren** [comment]
> Ignore scary warnings about trollius being deprecated.

Fantastic. Apparently it was deprecated two weeks ago.

**Comment by mikepurvis** [comment]
More info: http://trollius.readthedocs.org/deprecated.html

I don't have a clear sense what the implications are. Isn't it basically just a backport of the 3.4+ API to Python 2.x? Are there significant gaps? I assume that API is pretty much set in stone now, so it's not like there's tons to stay synchronized with.

**Comment by wjwwood** [comment]
> Fantastic. Apparently it was deprecated two weeks ago.

![double-facepalm](https://cloud.githubusercontent.com/assets/100427/13184934/824dee1c-d6f3-11e5-9575-3342a3536dc8.jpg)

> I don't have a clear sense what the implications are. Isn't it basically just a backport of the 3.4+ API to Python 2.x? Are there significant gaps? I assume that API is pretty much set in stone now, so it's not like there's tons to stay synchronized with.

Basically we needed it to support Python 2.x for this library and for anything that uses this library, including `catkin_tools`. There shouldn't be a problem (I think), but it makes the need to eventually move to Python 3 all the more real.

From: http://trollius.readthedocs.org/deprecated.html
> Python 2
Seriously? Come on! Stop procrastination and upgrade your code to Python 3!

I'm trying :sob:.

**Comment by jbohren** [comment]
@wjwwood So what's the plan going forward on this?

**Comment by wjwwood** [comment]
I don't know.

I'm not aware of any alternatives to trollius and I'm not interested in taking over maintenance of the package. However, we do need a substitute for asyncio in order to have Python 2 support. I suppose it's possible to implement the async functions in this library without either, but it would also mean `catkin_tools` couldn't use it. There is also a lot of intrinsic value in the way asyncio and trollius do subprocess execution...

One option is to coast with trollius until we can move away from Python 2. As @mikepurvis suggested, I think the main body of work for trollius is done and it implements everything we need. We should be able to work with their community to fix any issues that come up and hope nothing serious arrises. As for the debian, I can probably make a `python-trollius` debian for all the platforms we care about and stick that in our repository as well. I'd really rather not do that, but I don't see another option.

Another thought is to make `osrf_pycommon` as well as `catkin_tools` Python 3 only, but I think this is an extreme solution and will avoid it at all costs. Long term I think it would be ok, but so long as ROS is mainly using Python 2, it might not work for us. The only good thing about this approach is that `catkin_tools` running in Python 3 should have no bearing on the code it builds (like ROS 1 packages which could continue to use Python 2), so maybe that would be an implementation detail that users don't really care about. The biggest issue is getting the Python 2 and Python 3 versions of `catkin_tools` other dependencies installable side by side, e.g. `catkin_pkg`. That is currently not the case, i.e. `python-catkin-pkg` and `python3-catkin-pkg` are not side by side installable.

Yet another option is to not provide debians for `catkin_tools` at all and use Python 3 only.
We could tell people to install it from `pip3` using Python 3, but we'd have to ensure that it did not try to do so as Python 2 otherwise you get the issue of `pip2` overlaying our debian packages for common Python packages like `catkin_pkg`, see: http://answers.ros.org/question/49143/problems-with-rqt-groovy-ubuntu/?answer=49153#post-id-49153
We'd also have to make sure that installing things like `catkin_pkg` with `pip3` on Trusty does not impact the ROS 1 stuff at all (I think this is true, but we need to ensure it).
Or we could provide a convenient script for setting up `catkin_tools` on Ubuntu using Python3 and `virtualenv`. The `virtualenv` is the safest option, but the least convenient since it requires the user to source something before it can be used.

Anyone else have ideas?

**Comment by wjwwood** [comment]
Other thoughts about using `catkin_tools` with Python 3, while building ROS with Python 2:

- Make sure files generated by `catkin_tools` uses the Python interpreter that CMake finds, not the one `catkin_tools` uses.
- A conflict might arise where `catkin_pkg`, for example, is install by pip3 and from `apt-get` as `python-catkin-pkg` because executables from `catkin_pkg` would be in `/usr/bin` (`apt-get`/Python 2) and `/usr/local/bin` (`pip3`/Python 3). So when the user does something like `catkin_create_pkg` they'll get the Python 3/`pip3` version not the Python 2/`apt-get` version.

**Comment by mikepurvis** [comment]
Having catkin_tools using a different python from catkin's python sounds like a nightmare, but I don't really have a full grasp of the implications.

Another gross-but-maybe-okay path would be to simply bundle trollius with osrf_pycommon. Copy the whole module folder, and change imports to use the bundled version. Then you get distribution kind of for free— at the cost of remembering to periodically freshen it as updates trickle in upstream.

**Comment by jbohren** [comment]
Thanks for the overview @wjwwood. From what I gather, `trollius` 2.1 should probably work until the end of time in Python2, and the only issues going forward are the potential pitfalls from APIs or behaviors changing in future Python3 versions. `osrf_pycommon` uses `trollius` in Python2 and `asyncio` in Python3, all we'd need to do is future-proof `catkin_tools` to do the same, and then we should be fine.

If it's not too much overhead, I think creating a `python-trollius` debian package would be appropriate. If we do that then we can get this stuff released and keep moving forward.

**Comment by wjwwood** [comment]
Just an update: I've been working on how I might include the trollius 2.1 release in osrf_pycommon in a reasonable way as @mikepurvis suggested. It's even more narrow, basically I only need to embedded it (install it along with `osrf_pycommon`) if packaging for a Debian binary. In all other cases I can avoid installing it. Also, even in the case that it was installed with a Debian binary I only need to `import` the embedded version if `trollius` cannot be imported from the system. For example, if someone installs `osrf_pycommon` from our Debian binary and then installs `trollius` from `pip`, it will use the `pip` version.

I'm still working out if it is reasonable to embed `trollius` in this way and what impact it will have on the calling code. If this doesn't end up working out, then I guess I'll just roll a `trollius` Debian for our use and put it in the ros package repository. The down side to that approach is that it will conflict with versions installed with `pip` and if someone else added a `python-trollius` package for their use. In the embedding case, it is only put on the `PYTHONPATH` iff `import trollius` already fails and only when using `osrf_pycommon`.

**Comment by wjwwood** [comment]
If anyone's interested, I opened: https://github.com/osrf/osrf_pycommon/pull/19

It:

- conditionally embeds trollius when making a .deb
- does not put trollius on the path, i.e. `import trollius` is still not possible after installing this
- it does put it on the path after `import osrf_pycommon.vendor.trollius_helper` is imported
  - but only if it was not found in the system first

I think this should be ok. On all other systems (which use `pip`) I still just add `trollius` as a dependency in the `setup.py`.

**Comment by wjwwood** [comment]
Another update. I released `0.1.0` :tada:. Unfortunately the deb for Python2 doesn't work because it tries to byte-compile a Python3-only file in the post install hook. I'm looking into a way to fix that.

**Comment by wjwwood** [comment]
Ok, `0.1.1` is released and works from both `pip` and `apt-get` with `catkin_tools@master`.

**Comment by jbohren** [comment]
Awesome!

**Comment by davetcoleman** [comment]
Thanks!
